In [1]:
import tensorflow as tf
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing.text import Tokenizer

2024-06-11 11:30:08.712411: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-06-11 11:30:08.712475: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-06-11 11:30:08.712502: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-06-11 11:30:08.719066: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
import pandas as pd
import numpy as np

df=pd.read_csv("datasets/cleaned.csv")
df.head()
sents=df['text'].tolist()
sents[:4]

['A Beginner’s Guide to Word Embedding with Gensim Word2Vec Model',
 'Hands-on Graph Neural Networks with PyTorch & PyTorch Geometric',
 'How to Use ggplot2 in Python',
 'Databricks: How to Save Files in CSV on Your Local Computer']

Tokenizing the each sentences into numbers

In [3]:
import tensorflow as tf
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing.text import Tokenizer

In [4]:
tokenizer=Tokenizer()
tokenizer.fit_on_texts(sents)
tokenizer.word_index

{'to': 1,
 'the': 2,
 'a': 3,
 'of': 4,
 'how': 5,
 'and': 6,
 'in': 7,
 'your': 8,
 'for': 9,
 'you': 10,
 'with': 11,
 'is': 12,
 '—': 13,
 'data': 14,
 'why': 15,
 'i': 16,
 'what': 17,
 'on': 18,
 'learning': 19,
 'from': 20,
 'an': 21,
 'be': 22,
 'my': 23,
 'writing': 24,
 'are': 25,
 'it': 26,
 'can': 27,
 'using': 28,
 'design': 29,
 'ux': 30,
 'machine': 31,
 'about': 32,
 'do': 33,
 'not': 34,
 'python': 35,
 'ai': 36,
 'life': 37,
 'that': 38,
 'when': 39,
 'should': 40,
 'we': 41,
 '5': 42,
 'science': 43,
 'make': 44,
 'time': 45,
 'need': 46,
 'as': 47,
 '3': 48,
 'more': 49,
 'at': 50,
 'business': 51,
 'or': 52,
 'part': 53,
 'have': 54,
 'new': 55,
 'work': 56,
 'don’t': 57,
 'up': 58,
 'by': 59,
 'write': 60,
 'get': 61,
 'use': 62,
 'guide': 63,
 'will': 64,
 'marketing': 65,
 '1': 66,
 'ways': 67,
 'deep': 68,
 'best': 69,
 'analysis': 70,
 'first': 71,
 '2019': 72,
 'product': 73,
 'better': 74,
 'things': 75,
 'know': 76,
 'this': 77,
 'neural': 78,
 'future': 79,

In [5]:
len(tokenizer.word_index)

8229

In [5]:
[tokenizer.texts_to_sequences([t])[0] for t in sents][:5]

[[3, 668, 63, 1, 446, 1511, 11, 2448, 3644, 94],
 [1850, 18, 733, 78, 99, 11, 339, 339, 1851],
 [5, 1, 62, 3645, 7, 35],
 [3646, 5, 1, 260, 1279, 7, 2449, 18, 8, 932, 216],
 [3, 186, 59, 186, 477, 4, 1852, 1280, 6, 1512]]

Creating a Input Output Sequence for Training

In [6]:
input_sequences=[]
for t in sents:
    tokenized_sent=tokenizer.texts_to_sequences([t])[0]

    for i in range(1,len(tokenized_sent)):
        input_sequences.append(tokenized_sent[:i+1])
input_sequences

[[3, 668],
 [3, 668, 63],
 [3, 668, 63, 1],
 [3, 668, 63, 1, 446],
 [3, 668, 63, 1, 446, 1511],
 [3, 668, 63, 1, 446, 1511, 11],
 [3, 668, 63, 1, 446, 1511, 11, 2448],
 [3, 668, 63, 1, 446, 1511, 11, 2448, 3644],
 [3, 668, 63, 1, 446, 1511, 11, 2448, 3644, 94],
 [1850, 18],
 [1850, 18, 733],
 [1850, 18, 733, 78],
 [1850, 18, 733, 78, 99],
 [1850, 18, 733, 78, 99, 11],
 [1850, 18, 733, 78, 99, 11, 339],
 [1850, 18, 733, 78, 99, 11, 339, 339],
 [1850, 18, 733, 78, 99, 11, 339, 339, 1851],
 [5, 1],
 [5, 1, 62],
 [5, 1, 62, 3645],
 [5, 1, 62, 3645, 7],
 [5, 1, 62, 3645, 7, 35],
 [3646, 5],
 [3646, 5, 1],
 [3646, 5, 1, 260],
 [3646, 5, 1, 260, 1279],
 [3646, 5, 1, 260, 1279, 7],
 [3646, 5, 1, 260, 1279, 7, 2449],
 [3646, 5, 1, 260, 1279, 7, 2449, 18],
 [3646, 5, 1, 260, 1279, 7, 2449, 18, 8],
 [3646, 5, 1, 260, 1279, 7, 2449, 18, 8, 932],
 [3646, 5, 1, 260, 1279, 7, 2449, 18, 8, 932, 216],
 [3, 186],
 [3, 186, 59],
 [3, 186, 59, 186],
 [3, 186, 59, 186, 477],
 [3, 186, 59, 186, 477, 4],
 [3

Padding

In [7]:
max_len=max([len(x) for x in input_sequences])
max_len

22

In [8]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_input_sequences=pad_sequences(input_sequences,maxlen=max_len,padding='pre')
padded_input_sequences

array([[  0,   0,   0, ...,   0,   3, 668],
       [  0,   0,   0, ...,   3, 668,  63],
       [  0,   0,   0, ..., 668,  63,   1],
       ...,
       [  0,   0,   0, ...,   3,  80,  51],
       [  0,   0,   0, ...,  80,  51, 722],
       [  0,   0,   0, ...,  51, 722, 542]], dtype=int32)

Let us consider all the texts before the last one will be our output

In [9]:
inputs=padded_input_sequences[:,:-1]
inputs

array([[  0,   0,   0, ...,   0,   0,   3],
       [  0,   0,   0, ...,   0,   3, 668],
       [  0,   0,   0, ...,   3, 668,  63],
       ...,
       [  0,   0,   0, ...,  60,   3,  80],
       [  0,   0,   0, ...,   3,  80,  51],
       [  0,   0,   0, ...,  80,  51, 722]], dtype=int32)

In [10]:
outputs=padded_input_sequences[:,-1]
outputs

array([668,  63,   1, ...,  51, 722, 542], dtype=int32)

In [11]:
inputs.shape,outputs.shape

((45577, 21), (45577,))

Converting Outputs to Categorical Classification

In [12]:
num_classes=len(tokenizer.word_index)+1
num_classes

8230

Rest of Stuff Done on Cloud for wikitext dataset

In [13]:
from tensorflow.keras.utils import to_categorical
y=to_categorical(outputs,num_classes=num_classes)
y,y.shape

(array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 1., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], dtype=float32),
 (45577, 8230))

LSTM Model

In [14]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense,GRU
from tensorflow.keras.layers import Bidirectional

In [19]:
model = Sequential()
model.add(Embedding(num_classes, 100, input_length=max_len-1))
model.add(Bidirectional(LSTM(150)))
model.add(Dense(num_classes, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam',metrics=['accuracy'])
model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_4 (Embedding)     (None, 21, 100)           823000    
                                                                 
 bidirectional_4 (Bidirecti  (None, 300)               226800    
 onal)                                                           
                                                                 
 dense_4 (Dense)             (None, 8230)              2477230   
                                                                 
Total params: 3527030 (13.45 MB)
Trainable params: 3527030 (13.45 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [20]:
model.fit(inputs,y,epochs=50) 

Epoch 1/50


2024-06-08 22:30:18.368700: I tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:442] Loaded cuDNN version 8700
2024-06-08 22:30:18.412903: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7efad42a6650 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2024-06-08 22:30:18.412965: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): NVIDIA GeForce GTX 1650, Compute Capability 7.5
2024-06-08 22:30:18.422742: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:269] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
2024-06-08 22:30:18.548884: I ./tensorflow/compiler/jit/device_compiler.h:186] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.


1425/1425 [==============================] - 29s 19ms/step - loss: 7.0782 - accuracy: 0.0736
Epoch 2/50
1425/1425 [==============================] - 19s 13ms/step - loss: 6.1943 - accuracy: 0.1204
Epoch 3/50
1425/1425 [==============================] - 18s 13ms/step - loss: 5.6025 - accuracy: 0.1479
Epoch 4/50
1425/1425 [==============================] - 19s 13ms/step - loss: 5.0104 - accuracy: 0.1800
Epoch 5/50
1425/1425 [==============================] - 17s 12ms/step - loss: 4.4376 - accuracy: 0.2202
Epoch 6/50
1425/1425 [==============================] - 17s 12ms/step - loss: 3.8975 - accuracy: 0.2783
Epoch 7/50
1425/1425 [==============================] - 17s 12ms/step - loss: 3.3982 - accuracy: 0.3507
Epoch 8/50
1425/1425 [==============================] - 17s 12ms/step - loss: 2.9534 - accuracy: 0.4211
Epoch 9/50
1425/1425 [==============================] - 18s 12ms/step - loss: 2.5681 - accuracy: 0.4866
Epoch 10/50
1425/1425 [==============================] - 17s 12ms/step - lo

In [39]:
text="Tommorow i" 

In [41]:
#tokenize
token_text=tokenizer.texts_to_sequences([text])[0]
#padding
padded_token_text=pad_sequences([token_text],maxlen=max_len-1,padding='pre')
#predict
output=model.predict(padded_token_text)
ind=np.argmax(output)
for word,index in tokenizer.word_index.items():
    if index==ind:
        text=text+" "+word
        break
text

1/1 [==============================] - 0s 21ms/step


'Tommorow i thought saving'

In [ ]:
# model.save('models/second_model')

INFO:tensorflow:Assets written to: models/second_model_wikitext/assets


INFO:tensorflow:Assets written to: models/second_model_wikitext/assets


In [6]:
import pickle

In [7]:
with open('models/tokenizer.pkl', 'wb') as handle:
    pickle.dump(tokenizer, handle, protocol=pickle.HIGHEST_PROTOCOL)